<?php
/**
 * Shanfix Technology BMS — command-line installer.
 *
 *   php install.php
 *
 * Creates config/config.php interactively, imports the schema and seed data,
 * and optionally sets the administrator password.
 *
 * Delete this file after a successful install on a production server.
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit("install.php can only be run from the command line.\n");
}

require_once __DIR__ . '/app/bootstrap.php';

const C_RESET = "\033[0m";
const C_GREEN = "\033[32m";
const C_RED   = "\033[31m";
const C_CYAN  = "\033[36m";
const C_DIM   = "\033[2m";

function say(string $msg, string $colour = ''): void
{
    echo $colour . $msg . ($colour ? C_RESET : '') . PHP_EOL;
}

function ask(string $question, string $default = '', bool $hidden = false): string
{
    $suffix = $default !== '' ? C_DIM . " [{$default}]" . C_RESET : '';
    echo $question . $suffix . ': ';

    if ($hidden && DIRECTORY_SEPARATOR !== '\\') {
        // Hide typed characters where the shell supports it.
        shell_exec('stty -echo 2>/dev/null');
        $answer = trim((string) fgets(STDIN));
        shell_exec('stty echo 2>/dev/null');
        echo PHP_EOL;
    } else {
        $answer = trim((string) fgets(STDIN));
    }

    return $answer !== '' ? $answer : $default;
}

function confirm(string $question, bool $default = true): bool
{
    $hint   = $default ? 'Y/n' : 'y/N';
    $answer = strtolower(ask($question . " ({$hint})"));

    if ($answer === '') {
        return $default;
    }

    return in_array($answer, ['y', 'yes'], true);
}

say('', '');
say('==============================================', C_CYAN);
say('  Shanfix Technology — Business Management', C_CYAN);
say('  Installer', C_CYAN);
say('==============================================', C_CYAN);
say('');

// ---------------------------------------------------------------------
// 1. Requirements
// ---------------------------------------------------------------------
say('Checking requirements…');

$problems = [];

if (version_compare(PHP_VERSION, '8.0.0', '<')) {
    $problems[] = 'PHP 8.0 or newer is required (found ' . PHP_VERSION . ').';
}

foreach (['pdo_mysql', 'mbstring', 'openssl', 'json'] as $ext) {
    if (!extension_loaded($ext)) {
        $problems[] = "The {$ext} extension is required but not loaded.";
    }
}

if (!extension_loaded('curl')) {
    say('  ! cURL is not loaded — KopoKopo STK Push will not work until it is enabled.', C_RED);
}

if (!extension_loaded('fileinfo')) {
    say('  ! fileinfo is not loaded — upload type checks will be skipped.', C_RED);
}

foreach ([STORAGE_PATH, CONFIG_PATH] as $dir) {
    if (!is_writable($dir)) {
        $problems[] = "Directory not writable: {$dir}";
    }
}

if ($problems) {
    say('');
    say('Cannot continue:', C_RED);
    foreach ($problems as $p) {
        say('  - ' . $p, C_RED);
    }
    exit(1);
}

say('  All requirements satisfied.', C_GREEN);
say('');

// ---------------------------------------------------------------------
// 2. Configuration
// ---------------------------------------------------------------------
$configPath = CONFIG_PATH . '/config.php';

if (is_file($configPath)) {
    say('config/config.php already exists.', C_CYAN);

    if (!confirm('Overwrite it?', false)) {
        say('Keeping the existing configuration.');
        $config = require $configPath;
        $db     = $config['db'];
    } else {
        $db = null;
    }
} else {
    $db = null;
}

if ($db === null) {
    say('');
    say('Database connection (from cPanel > MySQL Databases)', C_CYAN);

    $db = [
        'host'     => ask('  Host', 'localhost'),
        'port'     => (int) ask('  Port', '3306'),
        'database' => ask('  Database name'),
        'username' => ask('  Database user'),
        'password' => ask('  Database password', '', true),
        'charset'  => 'utf8mb4',
    ];

    if ($db['database'] === '' || $db['username'] === '') {
        say('Database name and user are required.', C_RED);
        exit(1);
    }

    say('');
    say('Application', C_CYAN);
    $appUrl = rtrim(ask('  Public URL (no trailing slash)', 'https://erp.shanfix.co.ke'), '/');
    $env    = confirm('  Is this a production server?', true) ? 'production' : 'development';

    $appKey = bin2hex(random_bytes(32));

    $template = <<<PHP
    <?php
    /**
     * Shanfix Technology BMS - configuration
     * Generated by install.php on %s
     */

    return [

        'db' => [
            'host'     => %s,
            'port'     => %d,
            'database' => %s,
            'username' => %s,
            'password' => %s,
            'charset'  => 'utf8mb4',
        ],

        'app' => [
            'name'             => 'Shanfix Technology',
            'url'              => %s,
            'env'              => %s,
            'debug'            => %s,
            'timezone'         => 'Africa/Nairobi',
            'locale'           => 'en_KE',
            'session_lifetime' => 480,
        ],

        'security' => [
            // Encrypts KopoKopo secrets at rest. Changing this makes stored
            // secrets unreadable — they would need to be re-entered.
            'app_key'            => %s,
            'secure_cookies'     => %s,
            'max_login_attempts' => 5,
            'lockout_minutes'    => 15,
        ],

        'uploads' => [
            'max_size_mb'   => 8,
            'allowed_types' => ['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'zip'],
        ],
    ];
    PHP;

    $contents = sprintf(
        $template,
        date('Y-m-d H:i'),
        var_export($db['host'], true),
        $db['port'],
        var_export($db['database'], true),
        var_export($db['username'], true),
        var_export($db['password'], true),
        var_export($appUrl, true),
        var_export($env, true),
        $env === 'production' ? 'false' : 'true',
        var_export($appKey, true),
        str_starts_with($appUrl, 'https://') ? 'true' : 'false'
    );

    // Strip the heredoc indentation.
    $contents = preg_replace('/^    /m', '', $contents);

    if (file_put_contents($configPath, $contents) === false) {
        say('Could not write config/config.php', C_RED);
        exit(1);
    }

    @chmod($configPath, 0640);
    say('');
    say('  config/config.php written.', C_GREEN);
}

// ---------------------------------------------------------------------
// 3. Connect
// ---------------------------------------------------------------------
say('');
say('Connecting to the database…');

try {
    $pdo = new PDO(
        sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4', $db['host'], $db['port'] ?? 3306, $db['database']),
        $db['username'],
        $db['password'],
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
    );
} catch (PDOException $e) {
    say('  Connection failed: ' . $e->getMessage(), C_RED);
    say('  Check the credentials in config/config.php and run this installer again.');
    exit(1);
}

say('  Connected to ' . $db['database'] . '.', C_GREEN);

// ---------------------------------------------------------------------
// 4. Schema
// ---------------------------------------------------------------------
$existing = (int) $pdo->query(
    "SELECT COUNT(*) FROM information_schema.tables
      WHERE table_schema = " . $pdo->quote($db['database']) . "
        AND table_name IN ('users','clients','documents')"
)->fetchColumn();

$runSchema = true;

if ($existing > 0) {
    say('');
    say('  This database already contains Shanfix tables.', C_CYAN);
    $runSchema = confirm('  Re-run schema.sql? (safe — it uses CREATE TABLE IF NOT EXISTS)', false);
}

if ($runSchema) {
    say('');
    say('Importing schema…');
    runSqlFile($pdo, BASE_PATH . '/database/schema.sql');
    say('  Schema imported.', C_GREEN);
}

$userCount = (int) $pdo->query('SELECT COUNT(*) FROM users')->fetchColumn();

if ($userCount === 0) {
    say('');
    say('Importing starter data (categories, sample services and stock)…');
    runSqlFile($pdo, BASE_PATH . '/database/seed.sql');
    say('  Starter data imported.', C_GREEN);
} else {
    say('');
    say('  ' . $userCount . ' user account(s) already exist — skipping seed data.', C_CYAN);
}

// ---------------------------------------------------------------------
// 5. Administrator
// ---------------------------------------------------------------------
say('');
say('Administrator account', C_CYAN);

$admin = $pdo->query("SELECT id, email FROM users WHERE role = 'admin' ORDER BY id LIMIT 1")->fetch(PDO::FETCH_ASSOC);

if ($admin && confirm('  Set a new password for ' . $admin['email'] . ' now?', true)) {
    $email = ask('  Email', $admin['email']);

    while (true) {
        $password = ask('  New password (min 8 characters)', '', true);

        if (strlen($password) < 8) {
            say('  Too short — use at least 8 characters.', C_RED);
            continue;
        }

        $confirmPassword = ask('  Confirm password', '', true);

        if ($password !== $confirmPassword) {
            say('  Passwords do not match. Try again.', C_RED);
            continue;
        }

        break;
    }

    $stmt = $pdo->prepare('UPDATE users SET email = ?, password_hash = ? WHERE id = ?');
    $stmt->execute([strtolower($email), password_hash($password, PASSWORD_DEFAULT), $admin['id']]);

    say('  Administrator updated.', C_GREEN);
} elseif ($admin) {
    say('  Default login: ' . $admin['email'] . ' / Shanfix@2026', C_CYAN);
    say('  Change this password immediately after signing in.', C_RED);
}

// ---------------------------------------------------------------------
// Done
// ---------------------------------------------------------------------
say('');
say('==============================================', C_GREEN);
say('  Installation complete', C_GREEN);
say('==============================================', C_GREEN);
say('');
say('Next steps:');
say('  1. Point your domain or subdomain at the public/ folder.');
say('  2. Sign in and set your company details under Settings.');
say('  3. Add your KopoKopo API credentials under Settings > M-Pesa.');
say('  4. Delete install.php from the server.', C_RED);
say('');

/**
 * Execute a .sql file, splitting on semicolons at end of line.
 * The schema and seed files deliberately avoid stored procedures, so a
 * simple splitter is sufficient and keeps the installer dependency-free.
 */
function runSqlFile(PDO $pdo, string $file): void
{
    if (!is_file($file)) {
        say('  Missing SQL file: ' . $file, C_RED);
        exit(1);
    }

    $sql = (string) file_get_contents($file);

    // Strip full-line comments so they cannot confuse the splitter.
    $sql = preg_replace('/^\s*--.*$/m', '', $sql);

    $statements = array_filter(
        array_map('trim', preg_split('/;\s*[\r\n]/', $sql)),
        static fn(string $s): bool => $s !== ''
    );

    foreach ($statements as $statement) {
        try {
            $pdo->exec($statement);
        } catch (PDOException $e) {
            say('  SQL error: ' . $e->getMessage(), C_RED);
            say('  Statement: ' . substr($statement, 0, 160) . '…', C_DIM);
            exit(1);
        }
    }
}
